### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by npatel22526** [broadinstitute/SnowmanSV#2]
Hello, 

SnowmanSV seems great tool. 
I wanted to give it test drive but unfortunately got stuck at very first step.
I was trying to install the and get  below error. 
fatal: reference is not a tree: 655d73fa9a9c98b66dc0bf991090e60dca8f7aa2 Unable to checkout '655d73fa9a9c98b66dc0bf991090e60dca8f7aa2' in submodule path 'SeqLib'

Seems like it was unable to obtain SeqLib with "--recursive" , hence I manually clone SeqLib , which working and it configured properly but when I ran make , got an error again. 

See attached log file.
[SnowmanSV.installation.Errorlog.txt](https://github.com/broadinstitute/SnowmanSV/files/1250248/SnowmanSV.installation.Errorlog.txt)

Best,
Nick

**Comment by walaj** [comment]
Hi Nick, 
That repos is very old. The project is now at github.com/wala/svaba This should fix your install issues. 
Best, 
Jeremiah

**Comment by npatel22526** [comment]
Thanks Walaj. Finished complete installation of "svaba".
